name: Punzai
favicon: null
layout_spectrum: 0.87537
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#292929'
    - '#669b8f'
    - '#a6cfeb'
    - '#e8423d'
  brandStrength: 0.5800576519686729
  lightness: 0.46168879489414394
  saturation: 0.535048360703513
  rhythmicContrast: 0.8083023780491203
purpose: []
